[package]
name = "yahtzeebot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
cached = "0.30.0"
counter = "0.5.3"
ordered-float = "2.10.0"